spring:
  config:
    activate:
      on-profile: dev
  security:
    oauth2:
      client:
        registration:
          miargentina:
            client-secret: ${MIARG_CLIENT_SECRET:stub-secret}
firebase:
  use-emulator: true
  emulator-host: localhost
  emulator-port: 8088
web3:
  rpc-url: http://127.0.0.1:8545
logging:
  level:
    com.mivoto: debug
