spring:
  security:
    oauth2:
      client:
        registration:
          miargentina:
            client-id: ${MIARG_CLIENT_ID}
            client-secret: ${MIARG_CLIENT_SECRET}
            scope: ${MIARG_SCOPE:openid,profile}
            redirect-uri: ${MIARG_REDIRECT_URI}
            authorization-grant-type: authorization_code
        provider:
          miargentina:
            authorization-uri: ${MIARG_AUTHORIZATION_URI}
            token-uri: ${MIARG_TOKEN_URI}
            jwk-set-uri: ${MIARG_JWK_SET_URI}
