server:
  port: 8080

app:
  firebase:
    projectId: ${FIREBASE_PROJECT_ID}

blockchain:
  baseUrl: http://mock-blockchain-service:8081

logging:
  level:
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: DEBUG
    