server:
  port: ${PORT:8080}

app:
  firebase:
    projectId: ${FIREBASE_PROJECT_ID}
  cors:
    allowed-origins:
      - ${FRONT_URL:https://mi-voto-theta.vercel.app}
      - http://localhost:5173
      - http://127.0.0.1:5173
    allowed-origin-patterns:
      - https://*.vercel.app
    allowed-methods:
      - GET
      - POST
      - OPTIONS
    max-age-seconds: 3600

blockchain:
  providerUrl: ${BLOCKCHAIN_PROVIDER_URL:https://sepolia.infura.io/v3/YOUR_PROJECT_ID}
  privateKey: ${BLOCKCHAIN_PRIVATE_KEY:}
  electionContractAddress: ${BLOCKCHAIN_ELECTION_CONTRACT:0x0000000000000000000000000000000000000000}
  chainId: ${BLOCKCHAIN_CHAIN_ID:11155111}
  gasPrice: ${BLOCKCHAIN_GAS_PRICE:20000000000} # 20 gwei
  gasLimit: ${BLOCKCHAIN_GAS_LIMIT:600000}

logging:
  level:
    root: DEBUG
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: DEBUG

spring:
  config:
    import: optional:file:.env[.properties]
