spring:
  config:
    activate:
      on-profile: test
firebase:
  use-emulator: true
  emulator-host: localhost
  emulator-port: 8089
web3:
  rpc-url: http://127.0.0.1:8545
logging:
  level:
    root: warn
