spring:
  application:
    name: mivoto
  mvc:
    problemdetails:
      enabled: true
  security:
    oauth2:
      client:
        registration:
          miargentina:
            client-id: ${MIARG_CLIENT_ID}
            client-secret: ${MIARG_CLIENT_SECRET}
            scope: openid,profile
            redirect-uri: "{baseUrl}/auth/miargentina/callback"
            authorization-grant-type: authorization_code
        provider:
          miargentina:
            issuer-uri: ${MIARG_ISSUER_URI}
server:
  port: ${PORT:8080}

---
spring:
  config:
    activate:
      on-profile: dev
app:
  firebase:
    project-id: ${FIREBASE_PROJECT_ID:demo-mivoto}
    use-emulator: ${FIREBASE_USE_EMULATOR:true}
    emulator-host: ${FIREBASE_EMULATOR_HOST:localhost}
    emulator-port: ${FIREBASE_EMULATOR_PORT:8088}

---
spring:
  config:
    activate:
      on-profile: prod
app:
  firebase:
    project-id: ${FIREBASE_PROJECT_ID}
    use-emulator: ${FIREBASE_USE_EMULATOR:false}
web3:
  rpc-url: ${WEB3_RPC_URL}
  chain-id: ${WEB3_CHAIN_ID:80002}
  contract-address: ${VOTE_CONTRACT_ADDR}
  gas-price: ${WEB3_GAS_PRICE:20000000000}
  gas-limit: ${WEB3_GAS_LIMIT:6721975}
security:
  subject-pepper: ${ELIGIBILITY_SUBJECT_PEPPER}
  token-pepper: ${ELIGIBILITY_TOKEN_PEPPER}
jwt:
  issuer: ${JWT_ISSUER:https://mivoto.backend}
  jwk-set-uri: ${JWT_JWK_SET_URI}
  audience: ${JWT_AUDIENCE:mi-voto}
